//Create orphanage
POST http://localhost:3333/orphanages/ 
content-type: application/json

{
    "name": "Lar das crianças",
    "latitude": "-23.4963243",
    "longitude": "-46.6223594",
    "about": "orphanage for children",
    "instructions": "see instructions",
    "opening_hours": "from 8am to 7pm",
    "open_on_weekends": "true"
}

###
//List all itens
GET http://localhost:3333/orphanages/ 
content-type: application/json

###
//Get a item by id 
GET http://localhost:3333/orphanages/25
content-type: application/json